# This workflow will do a clean installation of node dependencies && run eslint to enforce coding styles from ".eslintrc.json".
name: Check ESLint on Pull Request or push

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: installing dependencies
        run: npm install
      - name: Fixing Files
        run: npx eslint . --ext .js --fix
